### ISSUE TITLE
download.file method for Windows

### ISSUE THREAD

**Issue by felixhaass** [walshc/nightlights#1]
Hi, thanks for the great package. 

Just a quick comment: I think in line https://github.com/walshc/nightlights/blob/master/R/downloadNightLights.R#L25 the `method` statement should be something like `wininet` or `internal` since `wget` won't work out of the box on all Windows machines whereas the other methods do.

Keep up the great work!

**Comment by walshc** [comment]
Hi Felix, I changed the method to `"auto"` which should work for different platforms (`wininet` will only work on Windows). I also added a new option in the `downloadNightLights()` function to allow you to specify a download method directly.

Thanks for bringing this to my attention. It would be great if you let me know if it still doesn't work (I am not able to test on Windows).
